package:
  name: reseq
  version: 1.1

source:
  path: ../../

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - boost
    - swig
  host:
    - python
    - zlib
    - bzip2
    - boost 
  run:
    - python
    - boost

about:
  home: https://github.com/schmeing/ReSeq/tree/devel
  license: MIT
